function bronze_svm_shap_baseline
% Bronze SVM + SHAP baseline (Codex Spec D)
% MATLAB R2021a+

%% Top-level parameters
rng(2026, 'twister');
Outer_K      = 5;
maxBO_iter   = 20;
innerHoldout = 0.2;
reportDir    = fullfile(pwd, 'SVM_Paper_Figures');
reviewPenalty = 0.20;

if ~exist(reportDir, 'dir')
    mkdir(reportDir);
end

%% Data loading
[fileName, filePath] = uigetfile('*.mat', 'Select feature_matrix.mat generated by build_svm_feature_matrix.m');
if isequal(fileName, 0)
    error('No input file selected.');
end
S = load(fullfile(filePath, fileName));
requiredVars = {'X_raw', 'Y', 'feat_names', 'nan_mask'};
for i = 1:numel(requiredVars)
    if ~isfield(S, requiredVars{i})
        error('Missing variable "%s" in input mat file.', requiredVars{i});
    end
end

X_raw = S.X_raw;
Y = S.Y;
feat_names = S.feat_names;
nan_mask = S.nan_mask;

if ~iscategorical(Y)
    Y = categorical(Y);
end
if isrow(nan_mask)
    nan_mask = nan_mask(:);
end
if any(nan_mask)
    warning('NaN detected in %d sample(s): %s', nnz(nan_mask), mat2str(find(nan_mask(:))'));
end

classNames = categories(Y);
if numel(classNames) ~= 2
    error('Binary classification required. Found %d classes.', numel(classNames));
end
if any(strcmp(classNames, 'Mineralized'))
    mineralizedLabel = 'Mineralized';
else
    mineralizedLabel = classNames{1};
    warning('Class "Mineralized" not found. Using "%s" as positive class.', mineralizedLabel);
end

N = size(X_raw, 1);
classCounts = countcats(removecats(Y));
minClassCount = min(classCounts);
if minClassCount < 2
    error('Each class must have at least 2 samples for train/test split.');
end

maxStratifiedK = min([Outer_K, N, minClassCount]);
if maxStratifiedK < 2
    maxStratifiedK = N;
end
if maxStratifiedK < Outer_K
    warning('Outer_K=%d is too large for minority class count=%d; using K=%d.', Outer_K, minClassCount, maxStratifiedK);
end
foldId = makeStratifiedFolds(Y, maxStratifiedK, 2026);
save('shared_fold_ids.mat', 'foldId', 'maxStratifiedK');
fprintf('Fold IDs saved to shared_fold_ids.mat for cross-pipeline alignment.\n');
numFolds = maxStratifiedK;

% Storage
results = struct;
results.fold = repmat(struct(), numFolds, 1);
accs = zeros(numFolds,1);
f1s = zeros(numFolds,1);
baccs = zeros(numFolds,1);
aucs = zeros(numFolds,1);

allScores = cell(numFolds,1);
allLabels = cell(numFolds,1);

bestFoldIdx = 1;
bestFoldAUC = -inf;
bestSVM_prob = [];
bestXTestNorm = [];
bestShapValues = [];

%% Nested CV loop
for f = 1:numFolds
    teIdx = (foldId == f);
    trIdx = ~teIdx;

    Xtr = X_raw(trIdx, :);
    Ytr = Y(trIdx);
    Xte = X_raw(teIdx, :);
    Yte = Y(teIdx);

    % Foldwise NaN imputation by train median
    medFold = nanmedian(Xtr, 1);
    medFold(isnan(medFold)) = 0;
    Xtr = fillmissing(Xtr, 'constant', medFold);
    Xte = fillmissing(Xte, 'constant', medFold);

    % Foldwise z-score normalization
    mu_fold = mean(Xtr, 1);
    sigma_fold = std(Xtr, 0, 1);
    sigma_fold(sigma_fold == 0) = 1;

    XtrN = (Xtr - mu_fold) ./ sigma_fold;
    XteN = (Xte - mu_fold) ./ sigma_fold;

    % Inner holdout BO
    [innerTrIdx, innerValIdx] = makeStratifiedHoldout(Ytr, innerHoldout, 1000 + f);
    XinnerTr = XtrN(innerTrIdx, :);
    YinnerTr = Ytr(innerTrIdx);
    XinnerVal = XtrN(innerValIdx, :);
    YinnerVal = Ytr(innerValIdx);

    optimVars = [ ...
        optimizableVariable('BoxConstraint',[1e-2,1e3],'Transform','log')
        optimizableVariable('KernelScale',[1e-2,1e2],'Transform','log')
    ];

    ObjFcn = @(optVars) svmBayesObjective(optVars, XinnerTr, YinnerTr, XinnerVal, YinnerVal);
    BO = bayesopt(ObjFcn, optimVars, ...
        'MaxObjectiveEvaluations', maxBO_iter, ...
        'Verbose', 0, ...
        'PlotFcn', []);

    bestHyperparams = BO.XAtMinObjective;

    finalSVM = fitcsvm(XtrN, Ytr, ...
        'KernelFunction', 'rbf', ...
        'BoxConstraint', bestHyperparams.BoxConstraint, ...
        'KernelScale', bestHyperparams.KernelScale, ...
        'Standardize', false, ...
        'ClassNames', categories(Y));

    finalSVM_prob = finalSVM; % Compatibility mode: use raw SVM scores (no fitPosterior)

    [YPred, YScore] = predict(finalSVM_prob, XteN);
    YPred = categorical(YPred, categories(Y));

    [acc, f1, bacc, cm] = calcMetricsBinary(Yte, YPred, mineralizedLabel);
    posCol = find(strcmp(finalSVM_prob.ClassNames, mineralizedLabel), 1);
    scorePos = YScore(:, posCol);
    [FPR, TPR, ~, auc] = perfcurve(Yte, scorePos, mineralizedLabel);

    [uncertainIdx, band] = selectUncertaintyBand(scorePos, reviewPenalty);

    accs(f) = acc; f1s(f) = f1; baccs(f) = bacc; aucs(f) = auc;
    allScores{f} = scorePos;
    allLabels{f} = Yte;

    results.fold(f).acc = acc;
    results.fold(f).f1 = f1;
    results.fold(f).bacc = bacc;
    results.fold(f).auc = auc;
    results.fold(f).cm = cm;
    results.fold(f).bestHyperparams = bestHyperparams;
    results.fold(f).boTrace = extractBOTrace(BO);
    results.fold(f).uncertainIdx = uncertainIdx;
    results.fold(f).uncertainBand = band;

    % Figures per fold
    figCM = figure('Visible','off');
    cmChart = confusionchart(Yte, YPred);
    cmChart.FontName = 'Times New Roman';
    cmChart.FontSize = 12;
    title(sprintf('Fold %d Confusion Matrix', f));
    exportgraphics(figCM, fullfile(reportDir, sprintf('Fold%02d_ConfusionMatrix.png', f)), 'Resolution', 300);
    close(figCM);

    figROC = figure('Visible','off');
    plot(FPR, TPR, 'LineWidth', 1.5); grid on;
    xlabel('False Positive Rate'); ylabel('True Positive Rate');
    title(sprintf('Fold %d ROC (AUC = %.4f)', f, auc));
    set(gca, 'FontName', 'Times New Roman', 'FontSize', 12, 'LineWidth', 1.2);
    exportgraphics(figROC, fullfile(reportDir, sprintf('Fold%02d_ROC.png', f)), 'Resolution', 300);
    close(figROC);

    figBO = figure('Visible','off');
    tr = results.fold(f).boTrace;
    plot(tr.Iteration, tr.Objective, '-o', 'LineWidth', 1.2); grid on;
    xlabel('Iteration'); ylabel('Validation Error');
    title(sprintf('Fold %d BO Convergence', f));
    set(gca, 'FontName', 'Times New Roman', 'FontSize', 12, 'LineWidth', 1.2);
    exportgraphics(figBO, fullfile(reportDir, sprintf('Fold%02d_BO_Trace.png', f)), 'Resolution', 300);
    close(figBO);

    if auc > bestFoldAUC
        bestFoldAUC = auc;
        bestFoldIdx = f;
        bestSVM_prob = finalSVM_prob;
        bestXTestNorm = XteN;
    end
end

% ROC summary
figAll = figure('Visible','off'); hold on; grid on;
for f = 1:numFolds
    [FPR, TPR, ~, ~] = perfcurve(allLabels{f}, allScores{f}, mineralizedLabel);
    plot(FPR, TPR, 'LineWidth', 1.2, 'DisplayName', sprintf('Fold %d', f));
end
plot([0 1], [0 1], 'k--', 'LineWidth', 1.0, 'DisplayName', 'Chance');
legend('Location','southeast');
xlabel('False Positive Rate'); ylabel('True Positive Rate');
title('All Folds ROC Summary');
set(gca, 'FontName', 'Times New Roman', 'FontSize', 12, 'LineWidth', 1.2);
exportgraphics(figAll, fullfile(reportDir,'AllFolds_ROC_Summary.png'),'Resolution',300);
close(figAll);

%% SHAP / fallback permutation importance
shapAvailable = exist('shapley', 'file') == 2;
if shapAvailable
    try
        explainer = shapley(bestSVM_prob, bestXTestNorm, ...
            'Method', 'interventional', ...
            'QueryPoints', bestXTestNorm);
        shapValues = normalizeShapValues(explainer.ShapleyValues, size(bestXTestNorm, 2));
    catch
        shapAvailable = false;
        warning('shapley() failed. Falling back to permutation importance proxy.');
    end
end

if ~shapAvailable
    permImp = permutationFeatureImportance(bestSVM_prob, bestXTestNorm, mineralizedLabel);
    shapValues = repmat(permImp(:)', size(bestXTestNorm,1), 1);
end

bestShapValues = shapValues;

% SHAP beeswarm-like plot
mean_abs_shap = mean(abs(shapValues), 1);
[~, sort_idx] = sort(mean_abs_shap, 'descend');

figShap = figure('Visible','off'); hold on;
for i = 1:numel(sort_idx)
    j = sort_idx(i);
    x = double(shapValues(:, j));
    c = double(bestXTestNorm(:, j));
    nPts = min([numel(x), numel(c)]);
    x = x(1:nPts);
    c = c(1:nPts);
    y = i + (rand(nPts,1)-0.5)*0.4;
    scatter(x, y, 18, c, 'filled', 'MarkerFaceAlpha', 0.75);
end
colormap(turbo); colorbar;
yticks(1:numel(sort_idx));
yticklabels(feat_names(sort_idx));
xlabel('SHAP value'); ylabel('Feature');
title('SHAP Beeswarm (Best Fold)');
set(gca, 'YDir', 'reverse', 'FontName', 'Times New Roman', 'FontSize', 12, 'LineWidth', 1.2);
exportgraphics(figShap, fullfile(reportDir,'SHAP_Beeswarm.png'),'Resolution',300);
close(figShap);

% Feature importance barh
[sorted_imp, sort_idx2] = sort(mean_abs_shap, 'descend');
figImp = figure('Visible','off');
barh(sorted_imp, 'FaceColor', [0.2 0.5 0.8]);
set(gca, 'YDir', 'reverse', 'YTick', 1:numel(sort_idx2), 'YTickLabel', feat_names(sort_idx2), ...
    'FontName', 'Times New Roman', 'FontSize', 12, 'LineWidth', 1.2);
xlabel('mean(|SHAP|)'); ylabel('Feature');
title('SHAP Feature Importance');
exportgraphics(figImp, fullfile(reportDir,'SHAP_Feature_Importance.png'),'Resolution',300);
close(figImp);

%% Report
meanAcc = mean(accs); stdAcc = std(accs);
meanF1 = mean(f1s); stdF1 = std(f1s);
meanAUC = mean(aucs); stdAUC = std(aucs);

fprintf('SVM Acc = %.2f%% ± %.2f%%\n', meanAcc*100, stdAcc*100);
fprintf('SVM F1  = %.4f ± %.4f\n', meanF1, stdF1);
fprintf('SVM AUC = %.4f ± %.4f\n', meanAUC, stdAUC);

fprintf('\n=== MobileNetV2 vs SVM (manual input or load from MAT) ===\n');
fprintf('SVM      | Acc: %.2f%% | F1: %.4f | AUC: %.4f\n', meanAcc*100, meanF1, meanAUC);
fprintf('MobileNet| Acc: [input] | F1: [input] | AUC: [input]\n');

save(fullfile(reportDir, 'Bronze_SVM_SHAP_Baseline.mat'), ...
    'bestSVM_prob', 'bestFoldIdx', 'results', 'bestShapValues', 'accs', 'f1s', 'baccs', 'aucs');

end

function err = svmBayesObjective(optVars, Xtr, Ytr, Xval, Yval)
mdl = fitcsvm(Xtr, Ytr, ...
    'KernelFunction', 'rbf', ...
    'BoxConstraint', optVars.BoxConstraint, ...
    'KernelScale', optVars.KernelScale, ...
    'Standardize', false, ...
    'ClassNames', categories(Ytr));
YPred = predict(mdl, Xval);
err = mean(YPred ~= Yval);
end

function [acc, f1, bacc, cm] = calcMetricsBinary(yTrue, yPred, positiveClass)
classes = categories(yTrue);
yTrue = categorical(yTrue, classes);
yPred = categorical(yPred, classes);
cm = confusionmat(yTrue, yPred, 'Order', classes);
pos = find(strcmp(classes, positiveClass), 1);
neg = setdiff(1:2, pos);
TP = cm(pos,pos); FN = cm(pos,neg); FP = cm(neg,pos); TN = cm(neg,neg);
acc = (TP+TN) / sum(cm(:));
prec = TP / max(TP+FP, eps);
rec = TP / max(TP+FN, eps);
f1 = 2*prec*rec / max(prec+rec, eps);
sens = rec;
spec = TN / max(TN+FP, eps);
bacc = 0.5*(sens+spec);
end

function traceTbl = extractBOTrace(BO)
traceTbl = BO.ObjectiveTrace;
traceTbl = table((1:numel(traceTbl))', traceTbl(:), 'VariableNames', {'Iteration','Objective'});
end

function [idx, band] = selectUncertaintyBand(scorePos, reviewPenalty)
band = markUncertainByScore(scorePos, reviewPenalty);
idx = find(scorePos >= band(1) & scorePos <= band(2));
end

function band = markUncertainByScore(scorePos, reviewPenalty)
q = reviewPenalty/2;
lo = quantile(scorePos, q);
hi = quantile(scorePos, 1-q);
band = [lo, hi];
end


function svmOut = calibrateSVMPosterior(svmIn, Ytr)
% Legacy no-op kept for backward compatibility.
svmOut = svmIn; %#ok<NASGU>
if nargin > 1
    % no-op
end
warning('Posterior calibration disabled for compatibility with this MATLAB build; raw SVM scores are used.');
svmOut = svmIn;
end


function foldId = makeStratifiedFolds(Y, K, seed)
rng(seed, 'twister');
Y = removecats(categorical(Y));
classes = categories(Y);
N = numel(Y);
foldId = zeros(N,1);
for c = 1:numel(classes)
    idx = find(Y == classes{c});
    idx = idx(randperm(numel(idx)));
    for i = 1:numel(idx)
        foldId(idx(i)) = mod(i-1, K) + 1;
    end
end
end

function [trIdx, valIdx] = makeStratifiedHoldout(Y, holdoutRatio, seed)
rng(seed, 'twister');
Y = removecats(categorical(Y));
classes = categories(Y);
N = numel(Y);
valIdx = false(N,1);
for c = 1:numel(classes)
    idx = find(Y == classes{c});
    idx = idx(randperm(numel(idx)));
    nVal = max(1, round(numel(idx) * holdoutRatio));
    nVal = min(nVal, numel(idx)-1);
    valIdx(idx(1:nVal)) = true;
end
trIdx = ~valIdx;
end

function imp = permutationFeatureImportance(model, X, positiveClass)
[~, baseScoreMat] = predict(model, X);
posCol = find(strcmp(model.ClassNames, positiveClass), 1);
baseScore = mean(baseScoreMat(:, posCol));
imp = zeros(1, size(X,2));
for j = 1:size(X,2)
    Xp = X;
    Xp(:,j) = Xp(randperm(size(X,1)), j);
    [~, s] = predict(model, Xp);
    imp(j) = abs(baseScore - mean(s(:, posCol)));
end
end

function shapMat = normalizeShapValues(shapRaw, expectedFeatureCount)
% Convert various shapley() output formats into numeric [N x P] matrix.
if isnumeric(shapRaw)
    shapMat = shapRaw;
elseif istable(shapRaw)
    numMask = varfun(@isnumeric, shapRaw, 'OutputFormat', 'uniform');
    shapTblNum = shapRaw(:, numMask);
    shapMat = table2array(shapTblNum);
else
    error('Unsupported SHAP value type: %s', class(shapRaw));
end

if ~isnumeric(shapMat) || isempty(shapMat)
    error('SHAP values could not be converted to numeric matrix.');
end

if size(shapMat, 2) ~= expectedFeatureCount
    if size(shapMat, 1) == expectedFeatureCount
        shapMat = shapMat.';
    else
        error('SHAP dimension mismatch: expected %d features, got [%d x %d].', ...
            expectedFeatureCount, size(shapMat, 1), size(shapMat, 2));
    end
end
end